apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-mq
  template:
    metadata:
      labels:
        app: demo-mq
    spec:
      containers:
        - name: demo-mq
          image: rabbitmq:3.11.7-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: demo-mq
spec:
  selector:
    app: demo-mq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
    - protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 32002
